### ISSUE TITLE
Material idea: Pearl

### ISSUE THREAD

**Issue by pablode** [AntonPalmqvist/physically-based-api#43] opened 2023-10-31 12:16 UTC
Hello - thank you for this great resource!

I recently had the need for a [(cultured) pearl](https://en.wikipedia.org/wiki/Cultured_pearl) material - and the first thing I did was checking out this DB.

I think the material would make a great addition due to its need of SSS, clearcoat and possibly iridescence. There are a number of resources on the optical properties:
- https://www.nature.com/articles/s41598-021-94737-w
- https://www.gemstones-guide.com/Pearl.html
- https://rgl.s3.eu-central-1.amazonaws.com/media/papers/Guillen2020Pearlescent.pdf

**Comment by AntonPalmqvist** [comment] 2023-10-31 16:47
Hi, I'm glad you like it!

That's a great suggestion, and thank you for the excellent resources. I'll have a look!

**Comment by AntonPalmqvist** [comment] 2023-11-05 19:12
Here's my results so far. I tried to reproduce the most commonly depicted pearl type, with an off-white overall color and a green-pink tint.
Thanks again for the resources, they've been very helpful, especially the first one where they're actually doing renders themselves. However, as they mention in that paper, to accurately reproduce a pearl-like material, one would need a new shading model, as current models can't simulate the multilayer characteristics of the nacre.

With that said, I think you can get pretty close with the parameters available in Autodesk Standard Surface and OpenPBR:

- Base Color and Subsurface Color are set to a yellowish color
- Subsurface Radius is set to let red wavelengths a bit further, to give it a pinkish tint (I exaggerated the scale in the screenshot below to give an idea of how a small pearl would look like, as the shader ball is quite big). 
- IOR is set to 1.5, which is that of conchiolin, and Coat IOR is set to 1.68, which is that of aragonite. In reality there are many (hundreds?) of these layers interweaved.
- Thin Film Thickness is set to 380 nm and Thin Film IOR to 2. This is where I had to use a bit more creative freedom to get it to look more pearl-like. 380 nm is somewhat close to the values mentioned in the paper, but IOR of 2 is not really motivated, but I can imagine the multilayer structure, when approximated into one thin film layer, cold be resulting in a higher IOR.
- I was very temped to give it a non-PBR Metalness value of 0.4 because it made it look pretty good, but I decided to not do it in the end since it wouldn't really be physically correct and could mess things up for the rest of the layers. However, I think there could be some metal-like properties in the nacre, that are similar to a metallic coating on a transparent glass surface that could be explored further.

Here's the full stack of parameters used:
```
<input name="base_color" type="color3" value="0.95, 0.9, 0.8" />
<input name="specular_roughness" type="float" value="0.4" />
<input name="specular_ior" type="float" value="1.5" />
<input name="subsurface_weight" type="float" value="1.0" />
<input name="subsurface_color" type="color3" value="0.95, 0.9, 0.8" />
<input name="subsurface_radius_scale" type="color3" value="0.5, 0.3, 0.3" />
<input name="coat_weight" type="float" value="1" />
<input name="coat_roughness" type="float" value="0.15" />
<input name="coat_ior" type="float" value="1.68" />
<input name="thin_film_thickness" type="float" value="380" />
<input name="thin_film_ior" type="float" value="2" />
```

<img width="628" alt="Screenshot 2023-11-05 at 11 01 07" src="https://github.com/AntonPalmqvist/physically-based-api/assets/13031779/d78d35ea-6998-49d5-8eaf-49ea2ae516ef">

**Comment by pablode** [comment] 2023-11-05 22:49
That looks absolutely great! I guess it will take quite a while until there’s a pearlescence BSDF in MaterialX, but considering the shading model limitations, it’s pretty close!

**Comment by AntonPalmqvist** [comment] 2024-08-07 18:07
Closing this now, as Pearl was added to the database a while ago. Thanks again for the suggestion and resources!

The thumbnail was rendered with Cycles in Blender, and it looks a bit different from the results I got from Arnold.
Thin Film combined with SSS seems to look different in pretty much every renderer I've tried, so I recommend tweaking the parameters to your needs, as usual.

![image](https://github.com/user-attachments/assets/ea5a0443-d792-4fca-a319-27840a4ade1f)

**Closed by AntonPalmqvist** 2024-08-07 18:07 UTC
